# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
branches:
  only:
  - master
  - /^release-.*$/
  - /^v\d+\.\d+.*$/
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("Dispatcher"); Pkg.test("Dispatcher"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("Dispatcher"))
      Pkg.add("Coverage"); using Coverage
      Codecov.submit(process_folder())'
# generate docs
  - |
    julia -e '
      VERSION >= v"0.7.0-DEV.3656" && using Pkg
      VERSION >= v"0.7.0-DEV.5183" || cd(Pkg.dir("Dispatcher"))
      Pkg.add("Documenter");
      include(joinpath("docs", "make.jl"))'
